name: paulonia_image_service
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/texsmv/paulonia_image_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  paulonia_cache_image: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/default_placeholder.png